name: Report-HTML

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Report:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: CI
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: Use Python 3.10 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: run search.py
        env:
          TEAMS_HOOK: ${{ secrets.TEAMS_HOOK }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          python3 search.py -html
      - name: save changes
        run: |
          git config --global user.email "bot-parser@users.noreply.github.com"
          git config --global user.name "Bot-Parser"
          DATE=$(date -Iseconds)
          git add .
          git commit --all --message "Updated by Bot-Parser on $DATE" || echo "no changes to commit"
          git push
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cve-report
          path: |
            docs/index.html
